name: Electron Build (Ubuntu)

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # 最小权限原则

    steps:
    - name: Clean Electron Cache
      run: |
        rm -rf ~/.cache/electron
        rm -rf ~/.cache/electron-builder

    - uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-0 libnss3 libxss1 libasound2 libgbm-dev

    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"

    - run: npm ci

    - run: npm run electron:build -- --publish never

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "electron-build-ubuntu-$(date +%Y%m%d)"
        path: |
          dist_electron/*
          !dist_electron/*.yml
        retention-days: 7
